[package]
name = "examples-ethers"
version = "0.0.0"
publish = false

license.workspace = true
rust-version.workspace = true
edition.workspace = true

[dev-dependencies]
ethers.workspace = true
tokio = { workspace = true, features = ["macros"] }
eyre.workspace = true