[package]
name = "dydx-frontend"

[package.edition]
workspace = true

[package.version]
workspace = true

[dependencies.serde]
workspace = true

[dependencies]
yew = "0.19"
yew-router = "0.16"
web-sys = "0.3.57"
log = "0.4.6"
wasm-logger = "0.2.0"
